baseurl: /nantes
permalink: pretty
markdown: kramdown
paginate: 5
repo: nantes
github_org: maptime
maptime:
  chapter: Maptime Nantes
  twitter: MaptimeNantes
  twitterwordseparator: sur
  #disqus: YOUR DISQUS USERNAME
